In [ ]:
import pandas as pd
import sqlite3

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Customer-Churn.csv to Customer-Churn.csv

In [ ]:
df = pd.read_csv("Customer-Churn.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
conn = sqlite3.connect(":memory:")

In [ ]:
df.to_sql(
    "telco_churn",
    conn,
    if_exists="replace",
    index=False
)

7043

In [ ]:
query = """

SELECT *
FROM telco_churn
LIMIT 5

"""

pd.read_sql(query, conn)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

# **Calculate churn rate**

In [ ]:
query = """

SELECT
    Churn,
    COUNT(*) AS Customers
FROM telco_churn
GROUP BY Churn

"""

pd.read_sql(query, conn)

  Churn  Customers
0    No       5174
1   Yes       1869

# **Churn by Contract**

In [ ]:
query = """

SELECT
    Contract,
    Churn,
    COUNT(*) AS Total

FROM telco_churn

GROUP BY Contract, Churn

ORDER BY Contract

"""

pd.read_sql(query, conn)

         Contract Churn  Total
0  Month-to-month    No   2220
1  Month-to-month   Yes   1655
2        One year    No   1307
3        One year   Yes    166
4        Two year    No   1647
5        Two year   Yes     48

# **Average Monthly Charges**

In [ ]:
query = """

SELECT

Churn,

ROUND(
AVG(MonthlyCharges),2
) AS Avg_Monthly

FROM telco_churn

GROUP BY Churn

"""

pd.read_sql(query, conn)

  Churn  Avg_Monthly
0    No        61.27
1   Yes        74.44

# **Churn by Payment Method**

In [ ]:
query = """

SELECT

PaymentMethod,

COUNT(*) AS Customers,

SUM(

CASE

WHEN Churn='Yes'

THEN 1

ELSE 0

END

)

AS Churned

FROM telco_churn

GROUP BY PaymentMethod

ORDER BY Churned DESC

"""

pd.read_sql(query, conn)

               PaymentMethod  Customers  Churned
0           Electronic check       2365     1071
1               Mailed check       1612      308
2  Bank transfer (automatic)       1544      258
3    Credit card (automatic)       1522      232